"""
CIF Structure Validator
----------------------
Validates crystal structures generated by ML models against ground truth data from Materials Project.

What it does:
- Validates CIF files for chemical and structural validity
- Compares generated structures to ground truth using pymatgen's StructureMatcher
- Generates comprehensive statistics and visualizations
- Tracks success rates across multiple generation attempts

Input: CSV with columns [material_id, output (ground truth CIF), generation_0, generation_1, ...]
Output: 
  - CSV with validation results and RMS distances
  - Summary text file with statistics
  - 6 visualization plots (validity rates, RMS distribution, etc.)
  - Log file with processing details

Usage:
    python cif_structure_validator.py

Key parameters:
    - Structure matching: stol=0.5, ltol=0.3, angle_tol=10 (in compare_structures)
    - Validity cutoff: 0.5 Å minimum atomic distance
    - Minimum volume: 0.1 Å³
    
The script expects:
    - Input CSV in {output_dir}/ directory
    - pymatgen, pandas, numpy, matplotlib, seaborn, tqdm installed
    - ~2GB RAM per 1000 structures
    - ~2-5 minutes per 1000 structures

For different models/datasets, modify:
    - input_csv: path to your generated structures CSV
    - output_csv: naming convention for results
    - matching tolerances if structures are less/more precise
"""

import os
import sys
import numpy as np
import pandas as pd
from pymatgen.core import Structure, Element
from pymatgen.analysis.structure_matcher import StructureMatcher
from pymatgen.core.composition import Composition

# ===== ADD THESE NEW IMPORTS =====
from tqdm import tqdm
import logging
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import psutil
import subprocess
import argparse

parser = argparse.ArgumentParser(description="Validate generated CIFs vs. ground truth")
parser.add_argument("--input_csv", type=str, required=False, default="")
parser.add_argument("--output_dir", type=str, default="experiments")
parser.add_argument("--dataset", type=str, default="mp52")
parser.add_argument("--model", type=str, default="mistral")
parser.add_argument("--precision", type=str, default="16bit")
parser.add_argument("--seq_num", type=int, default=int(os.environ.get('SEQ_NUM','1')))
parser.add_argument("--run_id", type=str, default=datetime.now().strftime('%Y%m%d_%H%M%S'))
args, _ = parser.parse_known_args()

RUN_ID = args.run_id
DATASET = args.dataset
MODEL = args.model
PRECISION = args.precision
SEQ_NUM = args.seq_num

output_dir = f"{args.output_dir}/validation_{RUN_ID}_{DATASET}_{PRECISION}_{SEQ_NUM}sequences_{DATASET}_{MODEL}"
os.makedirs(output_dir, exist_ok=True)

# ===== ADD LOGGING SETUP HERE =====
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(f'{output_dir}/validation_log_{RUN_ID}.log'),
        logging.StreamHandler()
    ]
)

def get_gpu_info():
    try:
        output = subprocess.check_output(['nvidia-smi', '--query-gpu=name,memory.total', '--format=csv,noheader'])
        return output.decode('utf-8').strip()
    except Exception as e:
        return f"Could not query GPU info: {e}"

input_csv = args.input_csv if args.input_csv else ""
output_csv = f"{output_dir}/validation_{RUN_ID}_{SEQ_NUM}sequences_{DATASET}_{MODEL}_{PRECISION}.csv"

gpu_info = get_gpu_info()
logging.info(f"GPU Info: {gpu_info}")

# ===== YOUR EXISTING FUNCTIONS STAY THE SAME =====
def is_element_valid(composition):
    try:
        for element in composition.elements:
            Element(element.symbol)
        return True
    except:
        return False

def get_safe_space_group_number(structure):
    try:
        spg_info = structure.get_space_group_info()
        return spg_info[1] if spg_info else np.nan
    except Exception:
        return np.nan

def structure_validity(structure, cutoff=0.5):
    dist_mat = structure.distance_matrix
    dist_mat = dist_mat + np.diag(np.ones(dist_mat.shape[0]) * (cutoff + 10.))
    if dist_mat.min() < cutoff or structure.volume < 0.1:
        return False
    spg_number = get_safe_space_group_number(structure)
    return not pd.isna(spg_number)

def validate_structure(cif_string):
    try:
        structure = Structure.from_str(cif_string, fmt="cif")
        valid_element = is_element_valid(structure.composition)
        valid_struct = structure_validity(structure)
        comp = structure.composition.reduced_formula if valid_element else np.nan
        spg = get_safe_space_group_number(structure) if valid_element and valid_struct else np.nan
        if valid_element and valid_struct:
            return True, structure, comp, spg
        else:
            return False, None, comp, spg
    except Exception:
        return False, None, np.nan, np.nan

def compare_structures(struct1, struct2, stol=0.5, ltol=0.3, angle_tol=10):
    matcher = StructureMatcher(stol=stol, ltol=ltol, angle_tol=angle_tol)
    try:
        rms_result = matcher.get_rms_dist(struct1, struct2)
        if rms_result is not None:
            return rms_result[0]
        return np.nan
    except:
        return np.nan

def near_miss_rms(struct1, struct2, stol=1.5, ltol=1.0, angle_tol=25):
    """How-close-was-it RMS for NON-matching pairs.

    The strict matcher (stol=0.5) returns NaN for a miss, so a binary match
    metric tells us nothing about *how wrong* a miss is — the exact reviewer
    complaint (framework §2, concern #2). This uses a very loose matcher to
    recover a continuous distance for near-misses. Returns the scalar RMS, or
    NaN if even the loose matcher cannot align the two structures.
    """
    try:
        matcher = StructureMatcher(stol=stol, ltol=ltol, angle_tol=angle_tol,
                                   primitive_cell=False)
        rms_result = matcher.get_rms_dist(struct1, struct2)
        if rms_result is not None:
            return rms_result[0]
        return np.nan
    except:
        return np.nan

# ===== MODIFY YOUR process_csv FUNCTION =====
def process_csv(input_csv, output_csv):
    df = pd.read_csv(input_csv)
    generation_columns = [col for col in df.columns if col.startswith("generation_")]
    
    # ADD: Logging
    logging.info(f"Processing {len(df)} samples with {len(generation_columns)} generations each")
    logging.info(f"Input file: {input_csv}")

    results = []
    # CHANGE: Replace df.iterrows() with tqdm for progress bar
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="Validating structures"):
        # REMOVE the old print statement
        # print(f"Processing row {idx + 1} of {len(df)}")
        
        material_id = row['material_id']
        ground_truth_cif = row['output']

        valid_gt, struct_gt, gt_composition, gt_spg = validate_structure(ground_truth_cif)
        
        # CHANGE: Use logging instead of print
        logging.debug(f"Material {material_id} - GT: {gt_composition}")

        result = {
            "material_id": material_id,
            "Groundtruth Composition": gt_composition,
            "Groundtruth SPG": gt_spg
        }

        for gen_col in generation_columns:
            generated_cif = row[gen_col]
            valid_gen, struct_gen, gen_composition, gen_spg = validate_structure(generated_cif)

            result[f"Validity_{gen_col}"] = "valid" if valid_gen else "invalid"
            result[f"Generated Composition_{gen_col}"] = gen_composition
            result[f"Generated SPG_{gen_col}"] = gen_spg

            if valid_gt and valid_gen:
                rms_distance = compare_structures(struct_gen,struct_gt)
                match = 1 if isinstance(rms_distance, float) and not np.isnan(rms_distance) else 0
                result[f"RMS Distance_{gen_col}"] = rms_distance
                result[f"Match_{gen_col}"] = match
                result[f"Error_{gen_col}"] = ""
                # Near-miss RMS: strict RMS if matched, else loose "how close" RMS.
                # Gives a continuous error signal for EVERY valid generation.
                result[f"NearMiss RMS_{gen_col}"] = (
                    rms_distance if match else near_miss_rms(struct_gen, struct_gt)
                )
            else:
                result[f"RMS Distance_{gen_col}"] = np.nan
                result[f"Match_{gen_col}"] = 0
                result[f"Error_{gen_col}"] = "Invalid CIF"
                result[f"NearMiss RMS_{gen_col}"] = np.nan

        results.append(result)

    result_df = pd.DataFrame(results)
    result_df.to_csv(output_csv, index=False, encoding="utf-8")
    
    match_columns = [f"Match_{col}" for col in generation_columns]
    any_match = result_df[match_columns].any(axis=1).sum()
    success_rate = 100 * any_match / len(result_df)

    failed_materials, spg_failure_df = analyze_failures(result_df, match_columns)
    failure_fig = create_failure_visualizations(failed_materials, spg_failure_df, result_df, match_columns)
    # Save failure analysis results
    failed_materials.to_csv(f'{output_dir}/failed_materials_analysis.csv', index=False)
    spg_failure_df.to_csv(f'{output_dir}/space_group_failure_rates.csv')

    # Save failure visualization
    failure_fig.savefig(f'{output_dir}/failure_analysis.png', dpi=300, bbox_inches='tight')

    # Add failure summary to your main summary
    with open(f'{output_dir}/validation_summary_with_failures.txt', 'w') as f:
        f.write(f"Validation Summary\n")
        f.write(f"Generated on: {datetime.now()}\n")
        f.write(f"Total samples: {len(result_df)}\n")
        f.write(f"Success rate: {success_rate:.1f}%\n\n")
        
        f.write(f"FAILURE ANALYSIS\n")
        f.write(f"="*50 + "\n")
        f.write(f"Complete failures: {len(failed_materials)}/{len(result_df)} ({len(failed_materials)/len(result_df)*100:.1f}%)\n\n")
        
        f.write(f"Top 5 Failing Space Groups:\n")
        for spg, data in spg_failure_df.head(5).iterrows():
            f.write(f"  {spg}: {data['failure_rate']:.1f}% ({data['failed']}/{data['total']})\n")
        
        f.write(f"\nMost Problematic Compositions:\n")
        for comp, count in failed_materials['Groundtruth Composition'].value_counts().head(5).items():
            f.write(f"  {comp}: {count} failures\n")

    print(f"\nFailure analysis complete! Check '{output_dir}/failed_materials_analysis.csv' for details.")
    # ADD: Log completion
    logging.info(f"Results saved to {output_csv}")
    
    # ADD: Call summary function
    print_summary_statistics(result_df, generation_columns)
    create_validation_plots(result_df, os.path.dirname(output_csv))
    
    logging.info(f"Memory usage after validation: {psutil.Process().memory_info().rss / 1024 ** 2:.2f} MB")

    return result_df

# ===== ADD NEW FUNCTIONS HERE =====
def print_summary_statistics(result_df, generation_columns):
    """Print comprehensive summary statistics"""
    print("\n" + "="*80)
    print("VALIDATION SUMMARY REPORT")
    print("="*80)
    
    total_samples = len(result_df)
    
    # Overall statistics for each generation
    for i, gen_col in enumerate(generation_columns, 1):
        valid_count = (result_df[f'Validity_{gen_col}'] == 'valid').sum()
        match_count = result_df[f'Match_{gen_col}'].sum()
        
        print(f"\nGeneration {i}:")
        print(f"  Valid structures: {valid_count}/{total_samples} ({100*valid_count/total_samples:.1f}%)")
        print(f"  Matched structures: {match_count}/{total_samples} ({100*match_count/total_samples:.1f}%)")
        
        # RMS statistics for matches
        rms_col = f'RMS Distance_{gen_col}'
        rms_values = result_df[result_df[f'Match_{gen_col}'] == 1][rms_col]
        if len(rms_values) > 0:
            print(f"  RMS stats: mean={rms_values.mean():.3f}Å, std={rms_values.std():.3f}Å")
            print(f"            min={rms_values.min():.3f}Å, max={rms_values.max():.3f}Å")
    
    # Best-of-N performance
    match_columns = [f'Match_{gen_col}' for gen_col in generation_columns]
    any_match = result_df[match_columns].any(axis=1).sum()
    success_rate = 100 * any_match / len(result_df)

    print(f"\n" + "-"*80)
    print(f"Overall Success Rate (at least one generation matches):")
    print(f"  {any_match}/{total_samples} ({success_rate:.1f}%)")
    
    # Composition accuracy
    print(f"\n" + "-"*80)
    print("Composition Accuracy:")
    for i, gen_col in enumerate(generation_columns, 1):
        comp_match = (result_df['Groundtruth Composition'] == 
                     result_df[f'Generated Composition_{gen_col}']).sum()
        print(f"  Generation {i}: {comp_match}/{total_samples} ({100*comp_match/total_samples:.1f}%)")
    
    # Space group accuracy
    print(f"\n" + "-"*80)
    print("Space Group Accuracy:")
    for i, gen_col in enumerate(generation_columns, 1):
        spg_match = (result_df['Groundtruth SPG'] == 
                    result_df[f'Generated SPG_{gen_col}']).sum()
        print(f"  Generation {i}: {spg_match}/{total_samples} ({100*spg_match/total_samples:.1f}%)")
    
    # ----- RMSE PANEL (reviewer concern #2: "how wrong is a miss") ----------
    # Strict matched-RMS (matches only) + near-miss RMS over ALL valid gens.
    rmse_lines = []
    rmse_lines.append("\n" + "="*80)
    rmse_lines.append("RMSE PANEL (StructureMatcher RMS, Å)")
    rmse_lines.append("="*80)

    strict_rms = []
    for gen_col in generation_columns:
        col = f'RMS Distance_{gen_col}'
        if col in result_df.columns:
            vals = result_df.loc[result_df[f'Match_{gen_col}'] == 1, col].dropna()
            strict_rms.extend(vals.tolist())
    strict_rms = np.asarray(strict_rms, dtype=float)
    if strict_rms.size:
        rmse_lines.append(f"Strict matched RMS  (n={strict_rms.size}): "
                          f"mean={strict_rms.mean():.3f}  median={np.median(strict_rms):.3f}  "
                          f"std={strict_rms.std():.3f}  min={strict_rms.min():.3f}  max={strict_rms.max():.3f}")
    else:
        rmse_lines.append("Strict matched RMS: no matches to report")

    near = []
    for gen_col in generation_columns:
        col = f'NearMiss RMS_{gen_col}'
        if col in result_df.columns:
            near.extend(result_df[col].dropna().tolist())
    near = np.asarray(near, dtype=float)
    if near.size:
        b1 = int((near < 0.5).sum())
        b2 = int(((near >= 0.5) & (near < 1.0)).sum())
        b3 = int(((near >= 1.0) & (near < 1.5)).sum())
        b4 = int((near >= 1.5).sum())
        rmse_lines.append(f"Near-miss RMS (all valid gens, n={near.size}): "
                          f"mean={near.mean():.3f}  median={np.median(near):.3f}  std={near.std():.3f}")
        rmse_lines.append(f"  bins:  <0.5: {b1}   0.5-1.0: {b2}   1.0-1.5: {b3}   >=1.5: {b4}")
    else:
        rmse_lines.append("Near-miss RMS: no valid generations to report")
    rmse_panel = "\n".join(rmse_lines)
    print(rmse_panel)

    # Save summary to text file
    summary_file = output_csv.replace('.csv', '_summary.txt')
    with open(summary_file, 'w') as f:
        f.write(f"Validation Summary for {input_csv}\n")
        f.write(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Total samples: {total_samples}\n")
        f.write(f"Success rate: {100*any_match/total_samples:.1f}%\n")
        f.write(rmse_panel + "\n")
        f.write(f"\nDetailed statistics saved in: {output_csv}\n")

    print(f"\nSummary saved to: {summary_file}")

def create_validation_plots(result_df, output_dir):
    """Create visualization plots"""
    generation_columns = [col.replace('Validity_', '') for col in result_df.columns 
                         if col.startswith('Validity_')]
    
    # 1. Validity rates bar plot (EXISTING CODE)
    plt.figure(figsize=(10, 6))
    validity_rates = []
    for gen_col in generation_columns:
        valid_rate = (result_df[f'Validity_{gen_col}'] == 'valid').mean() * 100
        validity_rates.append(valid_rate)
    
    plt.bar(range(1, len(generation_columns)+1), validity_rates)
    plt.xlabel('Generation Number')
    plt.ylabel('Validity Rate (%)')
    plt.title('CIF Structure Validity Rate by Generation')
    plt.ylim(0, 100)
    for i, rate in enumerate(validity_rates):
        plt.text(i+1, rate+1, f'{rate:.1f}%', ha='center')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'validity_rates.png'), dpi=300)
    plt.close()
    
    # 2. RMS distribution histogram (EXISTING CODE)
    plt.figure(figsize=(10, 6))
    all_rms = []
    for gen_col in generation_columns:
        rms_col = f'RMS Distance_{gen_col}'
        valid_rms = result_df[result_df[f'Match_{gen_col}'] == 1][rms_col]
        all_rms.extend(valid_rms.dropna())
    
    if all_rms:
        plt.hist(all_rms, bins=50, alpha=0.7, edgecolor='black')
        plt.axvline(np.mean(all_rms), color='red', linestyle='--', 
                   label=f'Mean: {np.mean(all_rms):.3f}Å')
        plt.xlabel('RMS Distance (Å)')
        plt.ylabel('Count')
        plt.title('Distribution of RMS Distances for Matched Structures')
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, 'rms_distribution.png'), dpi=300)
    plt.close()
    
    # 3. Success rate vs. space group (NEW)
    plt.figure(figsize=(12, 8))
    # Collect success rates by space group
    spg_success = {}
    for spg in result_df['Groundtruth SPG'].dropna().unique():
        spg_mask = result_df['Groundtruth SPG'] == spg
        spg_df = result_df[spg_mask]
        
        # Calculate success rate (any generation matches)
        match_cols = [f'Match_{gen_col}' for gen_col in generation_columns]
        success_rate = spg_df[match_cols].any(axis=1).mean() * 100
        count = len(spg_df)
        
        if count >= 5:  # Only include space groups with at least 5 samples
            spg_success[int(spg)] = (success_rate, count)
    
    if spg_success:
        # Sort by space group number
        sorted_spgs = sorted(spg_success.keys())
        success_rates = [spg_success[spg][0] for spg in sorted_spgs]
        counts = [spg_success[spg][1] for spg in sorted_spgs]
        
        # Create bar plot
        bars = plt.bar(range(len(sorted_spgs)), success_rates, alpha=0.7)
        
        # Color bars by success rate
        for i, bar in enumerate(bars):
            if success_rates[i] >= 80:
                bar.set_color('green')
            elif success_rates[i] >= 50:
                bar.set_color('orange')
            else:
                bar.set_color('red')
        
        plt.xlabel('Space Group Number')
        plt.ylabel('Success Rate (%)')
        plt.title('Success Rate by Space Group (≥5 samples)')
        plt.xticks(range(len(sorted_spgs)), sorted_spgs, rotation=90)
        
        # Add count labels on top of bars
        for i, (rate, count) in enumerate(zip(success_rates, counts)):
            plt.text(i, rate + 1, f'n={count}', ha='center', fontsize=8)
        
        plt.ylim(0, 105)
        plt.grid(axis='y', alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, 'success_by_spacegroup.png'), dpi=300)
    plt.close()
    
    # 4. Composition matching heatmap (NEW)
    plt.figure(figsize=(14, 10))
    
    # Get top compositions by frequency
    comp_counts = result_df['Groundtruth Composition'].value_counts()
    top_comps = comp_counts.head(30).index.tolist()  # Top 30 compositions
    
    if len(top_comps) > 5:
        # Create matrix for heatmap
        comp_matrix = np.zeros((len(top_comps), len(generation_columns)))
        
        for i, comp in enumerate(top_comps):
            comp_mask = result_df['Groundtruth Composition'] == comp
            comp_df = result_df[comp_mask]
            
            for j, gen_col in enumerate(generation_columns):
                # Calculate match rate for this composition and generation
                match_rate = comp_df[f'Match_{gen_col}'].mean() * 100
                comp_matrix[i, j] = match_rate
        
        # Create heatmap
        sns.heatmap(comp_matrix, 
                    xticklabels=[f'Gen {i+1}' for i in range(len(generation_columns))],
                    yticklabels=top_comps,
                    cmap='RdYlGn',
                    vmin=0, vmax=100,
                    annot=True, fmt='.0f',
                    cbar_kws={'label': 'Match Rate (%)'},
                    square=False)
        
        plt.title('Composition Match Rate Heatmap (Top 30 Compositions)')
        plt.xlabel('Generation')
        plt.ylabel('Composition')
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, 'composition_heatmap.png'), dpi=300)
    plt.close()
    
    # 5. Per-material success visualization (NEW)
    plt.figure(figsize=(16, 8))
    
    # Create a matrix showing success/failure for each material and generation
    n_materials = min(100, len(result_df))  # Limit to first 100 materials for visibility
    success_matrix = np.zeros((n_materials, len(generation_columns)))
    
    for i in range(n_materials):
        for j, gen_col in enumerate(generation_columns):
            success_matrix[i, j] = result_df.iloc[i][f'Match_{gen_col}']
    
    # Create custom colormap (0 = red/fail, 1 = green/success)
    colors = ['#ff4444', '#44ff44']
    n_bins = 2
    cmap = plt.cm.colors.ListedColormap(colors)
    
    # Plot
    plt.imshow(success_matrix, cmap=cmap, aspect='auto', interpolation='nearest')
    plt.colorbar(ticks=[0, 1], label='Match Status').set_ticklabels(['Fail', 'Success'])
    
    plt.xlabel('Generation')
    plt.ylabel('Material Index')
    plt.title(f'Per-Material Success Visualization (First {n_materials} Materials)')
    plt.xticks(range(len(generation_columns)), 
               [f'Gen {i+1}' for i in range(len(generation_columns))])
    
    # Add success rate annotation for each generation
    for j in range(len(generation_columns)):
        success_rate = success_matrix[:, j].mean() * 100
        plt.text(j, -5, f'{success_rate:.1f}%', ha='center', va='top')
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'per_material_success.png'), dpi=300)
    plt.close()
    
    # 6. Overall success summary pie chart (NEW BONUS)
    plt.figure(figsize=(8, 8))
    
    # Calculate different success levels
    match_cols = [f'Match_{gen_col}' for gen_col in generation_columns]
    no_match = (result_df[match_cols].sum(axis=1) == 0).sum()
    one_match = (result_df[match_cols].sum(axis=1) == 1).sum()
    multi_match = (result_df[match_cols].sum(axis=1) > 1).sum()
    
    # Create pie chart
    sizes = [no_match, one_match, multi_match]
    labels = ['No Match', 'One Match', 'Multiple Matches']
    colors = ['#ff6b6b', '#ffd93d', '#6bcf7f']
    explode = (0.05, 0, 0)
    
    plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%',
            shadow=True, startangle=90)
    plt.title('Overall Success Distribution')
    plt.axis('equal')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'success_distribution_pie.png'), dpi=300)
    plt.close()
    
    logging.info(f"All plots saved to {output_dir}")

def analyze_failures(result_df, match_columns):
    """
    Analyze patterns in failed structure predictions
    """
    print("\n" + "="*60)
    print("FAILURE ANALYSIS")
    print("="*60)
    
    # Identify completely failed materials
    failed_materials = result_df[result_df[match_columns].sum(axis=1) == 0]
    n_failed = len(failed_materials)
    n_total = len(result_df)
    
    print(f"\nTotal Failed Materials: {n_failed}/{n_total} ({n_failed/n_total*100:.1f}%)")
    
    # Analyze failures by space group
    print("\n--- Top 10 Most Failing Space Groups ---")
    failed_spgs = failed_materials['Groundtruth SPG'].value_counts()
    print(failed_spgs.head(10))
    
    # Calculate failure rate by space group
    spg_failure_rate = {}
    for spg in result_df['Groundtruth SPG'].unique():
        spg_materials = result_df[result_df['Groundtruth SPG'] == spg]
        spg_failed = spg_materials[spg_materials[match_columns].sum(axis=1) == 0]
        failure_rate = len(spg_failed) / len(spg_materials) * 100
        spg_failure_rate[spg] = {
            'failure_rate': failure_rate,
            'failed': len(spg_failed),
            'total': len(spg_materials)
        }
    
    # Sort by failure rate
    spg_failure_df = pd.DataFrame(spg_failure_rate).T
    spg_failure_df = spg_failure_df.sort_values('failure_rate', ascending=False)
    
    print("\n--- Space Groups with Highest Failure Rates ---")
    print(spg_failure_df.head(10))
    
    # Analyze failures by composition
    print("\n--- Top 10 Most Failing Compositions ---")
    failed_comps = failed_materials['Groundtruth Composition'].value_counts()
    print(failed_comps.head(10))
    
    # Identify patterns in failing compositions
    print("\n--- Composition Patterns in Failures ---")
    
    # Count elements in failed vs successful materials with pymatgen parsing
    def count_elements(comp_series):
        element_counts = {}
        for comp_str in comp_series:
            try:
                comp = Composition(comp_str)  
                for element in comp.elements:
                    elem_symbol = element.symbol
                    element_counts[elem_symbol] = element_counts.get(elem_symbol, 0) + 1
            except:
                pass
        return element_counts
    
    failed_elements = count_elements(failed_materials['Groundtruth Composition'])
    successful_materials = result_df[result_df[match_columns].sum(axis=1) > 0]
    success_elements = count_elements(successful_materials['Groundtruth Composition'])
    
    # Find elements that appear more in failures
    problematic_elements = []
    for elem in failed_elements:
        if elem in success_elements:
            fail_ratio = failed_elements[elem] / (failed_elements[elem] + success_elements[elem])
            if fail_ratio > 0.7:  # Elements that fail >70% of the time
                problematic_elements.append((elem, fail_ratio, failed_elements[elem]))
    
    print("\nProblematic Elements (>70% failure rate):")
    for elem, ratio, count in sorted(problematic_elements, key=lambda x: x[1], reverse=True):
        print(f"  {elem}: {ratio*100:.1f}% failure rate ({count} failures)")
    
    # Analyze by number of elements in composition
    def count_elements_in_formula(formula):
        """Count unique elements using pymatgen"""
        try:
            comp = Composition(formula)
            return len(comp.elements)
        except:
            return 0
    # def count_elements_in_formula(formula):
    #     # Count unique elements
    #     unique_elements = set()
    #     i = 0
    #     while i < len(formula):
    #         if formula[i].isupper():
    #             elem = formula[i]
    #             if i + 1 < len(formula) and formula[i + 1].islower():
    #                 elem += formula[i + 1]
    #                 i += 1
    #             unique_elements.add(elem)
    #         i += 1
    #     return len(unique_elements)
    
    failed_materials = failed_materials.copy()
    failed_materials['n_elements'] = failed_materials['Groundtruth Composition'].apply(count_elements_in_formula)    
    complexity_failure = failed_materials.groupby('n_elements').size()
    total_by_complexity = result_df.groupby(result_df['Groundtruth Composition'].apply(count_elements_in_formula)).size()
    complexity_failure_rate = (complexity_failure / total_by_complexity * 100).fillna(0)
    
    print("\n--- Failure Rate by Composition Complexity ---")
    for n_elem, rate in complexity_failure_rate.items():
        print(f"  {n_elem} elements: {rate:.1f}% failure rate")
    
    return failed_materials, spg_failure_df

def create_failure_visualizations(failed_materials, spg_failure_df, result_df, match_columns):
    """
    Create additional visualizations for failure analysis
    """
    fig, axes = plt.subplots(2, 2, figsize=(15, 12))
    fig.suptitle('Failure Analysis', fontsize=16)
    
    # 1. Failure rate by space group (top 20)
    ax1 = axes[0, 0]
    top_failing_spgs = spg_failure_df.head(20)
    bars = ax1.bar(range(len(top_failing_spgs)), top_failing_spgs['failure_rate'])
    ax1.set_xticks(range(len(top_failing_spgs)))
    ax1.set_xticklabels(top_failing_spgs.index, rotation=45, ha='right')
    ax1.set_ylabel('Failure Rate (%)')
    ax1.set_title('Top 20 Space Groups by Failure Rate')
    
    # Color bars by failure rate
    for i, bar in enumerate(bars):
        if top_failing_spgs['failure_rate'].iloc[i] == 100:
            bar.set_color('darkred')
        elif top_failing_spgs['failure_rate'].iloc[i] > 75:
            bar.set_color('red')
        elif top_failing_spgs['failure_rate'].iloc[i] > 50:
            bar.set_color('orange')
    
    # 2. Distribution of failures across generations
    ax2 = axes[0, 1]
    failed_by_gen = []
    for col in match_columns:
        n_failed = len(result_df[result_df[col] == 0])
        failed_by_gen.append(n_failed)
    
    ax2.plot(range(1, len(match_columns)+1), failed_by_gen, 'o-', linewidth=2, markersize=8)
    ax2.set_xlabel('Generation')
    ax2.set_ylabel('Number of Failed Predictions')
    ax2.set_title('Failures per Generation')
    ax2.grid(True, alpha=0.3)
    
    # 3. Complexity vs failure rate
    ax3 = axes[1, 0]
    complexity_data = result_df.copy()
    complexity_data['n_elements'] = complexity_data['Groundtruth Composition'].apply(
        lambda x: len(set([c for c in x if c.isupper()]))
    )
    complexity_data['failed'] = complexity_data[match_columns].sum(axis=1) == 0
    
    complexity_stats = complexity_data.groupby('n_elements')['failed'].agg(['sum', 'count'])
    complexity_stats['failure_rate'] = complexity_stats['sum'] / complexity_stats['count'] * 100
    
    ax3.bar(complexity_stats.index, complexity_stats['failure_rate'])
    ax3.set_xlabel('Number of Elements in Composition')
    ax3.set_ylabel('Failure Rate (%)')
    ax3.set_title('Failure Rate vs Composition Complexity')
    
    # 4. Heatmap of common failing element combinations
    ax4 = axes[1, 1]
    
    # Extract element pairs from failed compositions
    element_pairs = {}
    for comp in failed_materials['Groundtruth Composition']:
        elements = []
        i = 0
        while i < len(comp):
            if comp[i].isupper():
                elem = comp[i]
                if i + 1 < len(comp) and comp[i + 1].islower():
                    elem += comp[i + 1]
                    i += 1
                elements.append(elem)
            i += 1
        
        # Count pairs
        for i in range(len(elements)):
            for j in range(i+1, len(elements)):
                pair = tuple(sorted([elements[i], elements[j]]))
                element_pairs[pair] = element_pairs.get(pair, 0) + 1
    
    # Get top pairs
    top_pairs = sorted(element_pairs.items(), key=lambda x: x[1], reverse=True)[:10]
    pair_text = [f"{p[0][0]}-{p[0][1]}" for p in top_pairs]
    pair_counts = [p[1] for p in top_pairs]
    
    ax4.barh(pair_text, pair_counts)
    ax4.set_xlabel('Frequency in Failed Predictions')
    ax4.set_title('Most Common Element Pairs in Failures')
    
    plt.tight_layout()
    return fig

# ===== MODIFY THE MAIN EXECUTION =====
if __name__ == "__main__":
    # Process the CSV
    result_df = process_csv(input_csv, output_csv)
    
    # ADD: Final message
    print("\n" + "="*80)
    print("VALIDATION COMPLETE!")
    print("="*80)
    print(f"Check these files:")
    print(f"  - Results: {output_csv}")
    print(f"  - Summary: {output_csv.replace('.csv', '_summary.txt')}")
    print(f"  - Plots: {os.path.dirname(output_csv)}/")
    print(f"  - Log: validation_log_*.log")
